[package]
name = "music_player"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
crossterm = { version = "0.29.0" }
daemonize = "0.5.0"
lofty = "0.22.4"
rodio = { version = "0.21.1", features = ["symphonia-all"] }
